### ISSUE TITLE
[Feature request] filehandles

### ISSUE THREAD

**Issue by JaapWijnen** [mxcl/Path.swift#18]
As the isFile property is implemented I thought maybe it would be an idea to implement to get an optional FileHandle from a path. Let me know what you think, if you like it I can make a PR.

**Comment by mxcl** [comment]
If we were to be consistent with our current API this should be an extension for `FileHandle` that adds an initializer that takes a `Path`.

**Comment by JaapWijnen** [comment]
PR #19  created
