### ISSUE TITLE
[Swift 5] `swift build` fails because it has a minimum platform requirement

### ISSUE THREAD

**Issue by ollieatkinson** [mxcl/Path.swift#31]
```sh
$ swift build --configuration release -Xswiftc -static-stdlib --disable-sandbox
error: the product 'Path' requires minimum platform version 10.0 for tvos platform
error: the product 'Path' requires minimum platform version 3.0 for watchos platform
```

## Steps

1. Clone something which depends on Path.swift (e.g. swift-sh)
2. Execute `swift build`

## Environment 

- Xcode 10.2 Beta
- Swift 5

---

Am I missing something really obvious here or should this work?

**Comment by mxcl** [comment]
This is a bug in SwiftPM that I [reported](https://bugs.swift.org/browse/SR-9775) and is fixed in the next beta.

**Comment by mxcl** [comment]
You an workaround it by pinning to Path.swift@0.4.4

**Comment by mxcl** [comment]
I have fixed this by removing our platform requirements since they were the same as the defaults.

**Comment by ollieatkinson** [comment]
Confirmed working without pinning to 0.4.4 - awesome work!

**Comment by mxcl** [comment]
nps! If you found my help useful, please consider reimbursing my time by contributing to [my Patreon](https://patreon.com/mxcl). Thank you so much!
