### ISSUE TITLE
Refactor 

### ISSUE THREAD

**Issue by MarcSteven** [mxcl/Path.swift#32]
I think some var names are bad ,so should think about refactoring it ,for instance when I saw the var name ,if lack of comments I cannot understand the meaning about it ..

**Comment by mxcl** [comment]
You didn't specify which name you had trouble with.

**Comment by MarcSteven** [comment]
For instance  cwd variable name ,if lack of comment who can know its meanings???  @mxcl  only my tips, as a developer writing readable code is not easy ,naming is a tough topic

**Comment by mxcl** [comment]
`cwd` is a command line command. This library uses those names in general. If you aren’t familiar with them I recommend one of the alternatives.
