### ISSUE TITLE
Add `mimeType` property?

### ISSUE THREAD

**Issue by finestructure** [mxcl/Path.swift#46]
I need to guess mime types for files and have extended `Path` as follows:

```
extension Path {
    public var mimeType: String? {
        return MimeTypes[self.extension]
    }
}


let MimeTypes = [
    "323": "text/h323",
    ... <snip long list I grabbed from https://github.com/Microsoft/referencesource/blob/master/System.Web/MimeMapping.cs > ...
]
```

I know there's more to guessing mime types than this but maybe it's a useful start - at least it works for what I need it to do right now.

Is it worth opening a PR with this or is it out of scope?

**Comment by mxcl** [comment]
Thanks, but I feel bloating the library up with a big lookup table for a small use case isn't generally desired.
