### ISSUE TITLE
Issue with CLion.

### ISSUE THREAD

**Issue by Dash2507** [mxcl/Path.swift#49]
adding Path as dependency gives error in CLion.

> /Path.swift/Package.swift:15:67: error: use of unresolved identifier 'package'; did you mean 'Package'?
> ; import Foundation; print(String(data: try! JSONEncoder().encode(package), encoding: .utf8)!)
>                                                                   ^~~~~~~
>                                                                   Package
> PackageDescription.Package:1:20: note: 'Package' declared here
> final public class Package {
>                    ^

**Comment by mxcl** [comment]
Report the bug with CLion, this is perfectly valid.
