### ISSUE TITLE
Incorrect framework name when using CocoaPods

### ISSUE THREAD

**Issue by slice** [mxcl/Path.swift#51]
If Path.swift is added as a dependency using CocoaPods, `Path_swift.framework` ends up getting generated, not `Path.framework`. This leads to the user needing to do `import Path_swift` instead of `import Path`.

[`module_name`](https://guides.cocoapods.org/syntax/podspec.html#module_name) needs to be specified in the Podspec, as it is done in SQLite.swift [here](https://github.com/stephencelis/SQLite.swift/blob/0.12.0/SQLite.swift.podspec#L17).

**Comment by mxcl** [comment]
I have applied a fix to my script to fix this for the next release. I guess I will do a bump just to fix this.
