### ISSUE TITLE
[Feature request] Add .read_text() and read_bytes()

### ISSUE THREAD

**Issue by korakot** [mxcl/Path.swift#52]
Python's pathlib has them since version 3.5
It will make reading text much easier.

**Comment by mxcl** [comment]
We provide convenience functions for `Data.init` and `String.init` why are these not sufficient?

**Comment by korakot** [comment]
At first, I didn't see it in the examples.
They should be good enough. But I still prefer `read_text()` where you can chain the methods in logical order (you go into a directory, reach a file, then read its text.)

**Comment by mxcl** [comment]
We offer chaining for file system operations, and extensions for Apple API that takes string paths for the rest. I'd be convinced by a good example though.
