### ISSUE TITLE
suggestion: Additional convenience on Entries

### ISSUE THREAD

**Issue by ConfusedVorlon** [mxcl/Path.swift#53]
How about...

```
extension Array where Element == Entry {
    var paths:[Path] {
        return map { $0.path }
    }
}
```

This allows 

`let pathsInDirectory = try? myDirectoryPath.ls().paths`

**Comment by mxcl** [comment]
`1.0.0-alpha` removed the `Entry` type altogether and `ls()` now returns `[Path]`.

This was done as the `Entry` type was just fiddly and you can compose to get the same results that `Entry` gave you using eg. `filter` and `isDirectory`.

Though this could lead to race conditions, in real life this is unlikely and code concerned thus should use the new `Path.find()` builder function.

**Comment by ConfusedVorlon** [comment]
sounds good - I'll be happy to see the back of Entry :)
