### ISSUE TITLE
Path.home.find(): Value of type 'Any' has no member 'extension'

### ISSUE THREAD

**Issue by kaikuehne** [mxcl/Path.swift#56]
Hello,
first of all, thanks for providing this library. :-)
Secondly, I'm completely new to Swift, so bear with me if I'm just holding this wrong.

I was playing around with the API and cannot get one of the examples from the README to work.
This code...

```swift
Path.home.find().maxDepth(1).extension("swift").kind(.file) { path in
        //…
    }
```

... always gives me this error:

```
Value of type 'Any' has no member 'extension'
```

I tried to add `execute` to the call, to align it with the other examples, but that didn't help.
I'm using SPM to install version `1.0.0-alpha.3`. Any help is appreciated. Thanks!

**Comment by mxcl** [comment]
There is no `kind` function, use `type`. Did you get this from docs? If so where? I need to fix them.

**Comment by kaikuehne** [comment]
The code is a copy from https://github.com/mxcl/Path.swift/tree/1.0.0-alpha.3#directory-listings.

**Comment by mxcl** [comment]
```
Path.home.find().depth(max: 1).extension("swift").type(.file) { path in
      //…      
}
```

**Comment by mxcl** [comment]
Documentation fixed, thanks.

**Comment by kaikuehne** [comment]
Thanks!
