### ISSUE TITLE
Suggestion: Add option for .find() to ignore hidden files

### ISSUE THREAD

**Issue by ConfusedVorlon** [mxcl/Path.swift#76]
I love the easy recursive search. It would be great if this could be augmented with an option to ignore hidden files too.

perhaps:

`folderPath.find().depth(max: 2).extension("heic").type(.file).hidden(false)`

thanks again for a fantastic package

**Comment by mxcl** [comment]
PR welcome

**Comment by mxcl** [comment]
Publishing 1.4.0 with #77
